# Generated by Django 2.2.2 on 2019-07-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_colmeias', models.IntegerField()),
                ('apicultor', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Apicultor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('qtd_apiarios', models.IntegerField()),
                ('tipo_criador', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CaixaRacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiario', models.CharField(max_length=255)),
                ('identificador', models.CharField(max_length=255)),
                ('especie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Perda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_perda', models.CharField(max_length=255)),
                ('qtd_colmeias_perdidas', models.IntegerField()),
                ('data_registro_perda', models.DateTimeField(auto_now_add=True)),
                ('especie_perdida', models.CharField(max_length=255)),
                ('apiario', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-data_registro_perda'],
            },
        ),
    ]
